name: Integration Tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: [self-hosted,zendesk-stable]

    steps:
    - uses: zendesk/checkout@v2
    - uses: zendesk/setup-ruby@v1
    - name: Build and test with RSpec
      run: |
        gem install bundler --no-document
        bundle install --jobs 4 --retry 3
        bundle exec rspec --format documentation --require spec_helper --color --tag integration
